### ISSUE TITLE
Some choice libraries for you~

### ISSUE THREAD

**Issue by karai17** [JanWerder/awesome-love2d#2]
[anim8](https://github.com/kikito/anim8) - Animation library (supersedes AnAL)

[Simple Tiled Implementation](https://github.com/karai17/Simple-Tiled-Implementation) - Tiled map loader and renderer
[Winged Edge](https://github.com/karai17/lua-winged-edge) - Compile data into a Winged Edge data structure
[OBJ](https://github.com/karai17/lua-obj) - Wavefront Object loader

[LOVE3D](https://github.com/excessive/love3d) - 3D extensions to LOVE
[Cirno's Perfect Math Library](https://github.com/excessive/cpml) - A math library designed for games
[IQM](https://github.com/excessive/iqm) - Inter-Quake Model loader
[IQE](https://github.com/excessive/iqe) - Inter-Quake Export loader
[anim9](https://github.com/excessive/anim9) - An animation library (design to be used with IQM and IQE)
[i18n](https://github.com/excessive/i18n) - An internationalization library designed to help localize your game
[patchy](https://github.com/excessive/patchy) - A 9patch library
[cdata](https://github.com/excessive/cdata) - Serialize between Lua data and C data using LuaJIT's FFI

**Comment by JanWerder** [comment]
Thanks for the suggestions.
I added most of them.
I don't really understand path9 though and the documentation doesN't do a good job at explaining either.
