### ISSUE TITLE
Helpers vs. Utilities Category

### ISSUE THREAD

**Issue by ejmr** [JanWerder/awesome-love2d#20]
I was going to open a pull-request to add rxi's terrific [log.lua](https://github.com/rxi/log.lua) library to the list, but I couldn't decide whether it belonged under 'Helpers' or under 'Utilities'.  And when thinking about it, personally, I don't see a clear difference between the two categories.  Maybe we should either elaborate on their distinctions or, preferably in my opinion, merge the two together into one category?

**Comment by JanWerder** [comment]
My initial idea was:

Helper Libraries - Libraries that bundle common function and mostly serve multiple functions
Utilities - Small Meta-Libraries that help you achieve a very specific purpose which isn't game centric

But I understand your argument. Maybe we should rephrase it. Any suggestions? Vivid might be wrong in the helper category as well.

I would put log.lua in the utilities category.

**Comment by Guard13007** [comment]
Those descriptions as stated seem sufficiently defined and different to keep separate in my opinion. Are they not stated in the contributing and/or the actual list? If so, they should be.

**Comment by ejmr** [comment]
Thank you both for the feedback!

@JanWerder 

The distinction you describe---libraries of general purposes versus libraries of very specific purpose---is a useful one, in my opinion, and it would be useful to keep them in separate categories.  I don't think "Helper Libraries" and "Utilities" clearly convey that distinction though.  However, I also must admit I do not have better suggestions to provide; perhaps something like "General-Purpose Libraries" and "Game-Specific Libraries"?

I also think, regardless, we should heed the great suggestion by @Guard13007 and add a short description of categories in `CONTRIBUTING.md`.  For example, *I* know what 'Tweening' and 'Entity' and 'Serialization' mean in this context, but I can easily imagine someone just starting out who doesn't understand those terms in the context of game development.  If you think describing the categories in the Contributing document is a good idea then I'd be happy to write the patch for their inclusion.

**Comment by JanWerder** [comment]
I added a little description under the title of each Category. I would like to keep it there, since you shouldn't have to look in teh CONTRIBUTING.md to udnerstand the main list
