### ISSUE TITLE
Add description to categories

### ISSUE THREAD

**Issue by Yonaba** [JanWerder/awesome-love2d#21]
In my humble opinion, it would nice to have under each new category title a short description.
Something like, for example : 

## Helper Libraries
*Libraries that bundle common function and mostly serve multiple functions*
* lib1
* lib2

## Utilities
*Small Meta-Libraries that help you achieve a very specific purpose which isn't game centric*
* lib1
* lib2

This will help clarifying the purpose of every single category. As such, when making pull request, people will read them and decide where the new additions should go, or eventually suggest new categories.

**Comment by ejmr** [comment]
:+1: it consideration of issue #20

**Comment by JanWerder** [comment]
:+1:  I added a description for each category
