### ISSUE TITLE
Section for Testing Libraries/Tools

### ISSUE THREAD

**Issue by ejmr** [JanWerder/awesome-love2d#34]
Would it be useful to add a category to the list dedicated to unit-testing libraries and tools?  If so then I have a few that I'd like to submit.  But before doing so I'd like to hear feedback on the idea of putting them in their own section.

**Comment by JanWerder** [comment]
I think it's a good idea, otherwise the Utilities category might get too bloated

**Comment by ejmr** [comment]
That was my thought as well re. Utilities.  I'll prepare a series of patches for the new section.
